[build-system]
requires = ["setuptools>=38", "wheel", "numpy>=1.16.4", "cython>=0.29.12","scipy>=1.2.1", "eigenpip @ https://github.com/mohanwu/eigenpip/archive/main.zip"]
build-backend = "setuptools.build_meta"